### ISSUE TITLE
Source plugin causes JS error if opts.buttons = []

### ISSUE THREAD

**Issue by brandonkelly** [Redactor2/plugins#1]
_(Technically I think this is an issue with Redactor, but it affects the Source plugin, and there is no public issue tracker for Redactor so posting it here…)_

If you initialize a Redactor editor with the following options:

``` javascript
{
    'buttons': [],
    'plugins': ['source']
}
```

then the `toolbar.build()` function will bail early, because there are no toolbar buttons:

``` javascript
if (this.opts.buttons.length === 0)
{
    return;
}
```

However when the Source plugin is initailizing itself, it [calls](https://github.com/Redactor2/plugins/blob/master/source.js#L8) `this.button.addFirst()`, which assumes that there actually is a toolbar, etc.

A JS error will occur when it gets to this line of `this.button.build()`:

``` javascript
this.button.buttons.push($button);
```

because `this.buttons.buttons` never actually get set to an array. (And of course other aspects of the toolbar have not been initialized either.)

A workaround for this bug is to set `opts.buttons` to something bogus, just so Redactor actually initializes the toolbar:

``` javascript
{
    'buttons': ['foobar'],
    'plugins': ['source']
}
```

Although it would be nice if Redactor could just make sure the toolbar is actually initialized at the beginning of each of the toolbar/button APIs, and do it on the fly if it hasn't been.

**Comment by rosnovsky** [comment]
Fixed in Redactor II 1.2.3 update, thank you @brandonkelly!
