### ISSUE TITLE
Tableplugin does not work if redactor-textarea is inside an li 

### ISSUE THREAD

**Issue by phoebusryan** [Redactor2/plugins#4]
Hi there,
I just found a small issue for the table-plugin. It doesn't work when the textarea of the redactor is inside an li (and you don't have lists in your redactor-content).

The problem comes from this line:
https://github.com/Redactor2/plugins/blob/master/table.js#L210

Can you please fix that?

Thanks!

**Comment by dtdesign** [comment]
https://github.com/Redactor2/plugins/pull/3 contains a fix for this issue.

**Comment by phoebusryan** [comment]
Well that was fast! Thanks dtdesign
